### ISSUE TITLE
Link to jitsu package.json guide is broken

### ISSUE THREAD

**Issue by fredgalvao** [balderdashy/sails-docs#1000]
`http://package.json.nodejitsu.com/` doesn't seem to be the right/working link (anymore, at least).

[This guide](https://nodejitsu.com/documentation/appendix/package-json/) points to `http://package.json.jit.su/` instead, but it doesn't seem to be the right/working link either. Unfortunately I couldn't find a working version of such a guide, so I don't know what to even suggest.

**Comment by rachaelshaw** [comment]
@fredgalvao which page is this on?
