### ISSUE TITLE
SailJS.com "Take a Class" in footer redirects to Spanish website

### ISSUE THREAD

**Issue by AdJesumPerMariam** [balderdashy/sails-docs#1028]
I did not see a repo for SailsJS.com so I am creating an issue here. On SailsJS.com the footer link "Take a Class" brings you to https://platzi.com/cursos/javascript-pro/ which is in Spanish. Nothing wrong with Spanish, but this is being linked to from an English site and so I think it should only link out to a Spanish website if it is clear that the outbound site is in a different language.

https://courses.platzi.com/courses/sails-js/ is in English and could be a better link. The website is still a bit confusing because even on the English site there is some content that appears in Spanish.

**Comment by raqem** [comment]
@AdJesumPerMariam Thanks for pointing this out! We changed over the link.
