### ISSUE TITLE
Why `npm test` run sails server

### ISSUE THREAD

**Issue by JiDai** [balderdashy/sails-docs#1067]
I just created a Sails app, generate a blueprint and create a basic test following this tutorial : 
https://sailsjs.com/documentation/concepts/testing

When I run `npm test` the sails server run but I don't understand why.
The tests are well executed.

**Comment by mikermcneil** [comment]
Hi @JiDai - no worries, that's the intended behavior

**Comment by JiDai** [comment]
Ok thanks
