### ISSUE TITLE
res.json is NOT stringified

### ISSUE THREAD

**Issue by songangel72** [balderdashy/sails-docs#1135]
The documentation for this method states "Sends a JSON response composed of a stringified version of the specified data." but this is not happening.  On the client side when I console.log the typeof the data I get 'object'.  I had to stringify it myself on the server side using `return res.json(JSON.stringify(data));`

To duplicate the offending code is `return res.json({ rows: 5 });` but it would not stringify it.  I am not sure if this is a bug or a mistake in the documentation.  I am using Sails 1.1.0.

**Comment by rachaelshaw** [comment]
@songangel72 thanks for pointing out that this part of the docs needed clarification! The stringification that page mentioned happens in the middle. If you look at the raw request, the data should be stringified; it's the client that's decoding it.

Just updated that doc page: https://github.com/balderdashy/sails-docs/commit/257a964fe351ba71c48b2ab7a0034b5090aa3655#diff-e1922b8050e5157ba9d66247a7ea8d29

**Comment by songangel72** [comment]
@rachaelshaw I appreciate your response but in my example the client could not decode the data because it was receiving an object rather than a string.  My understanding is that res.json should be stringifying the data but it is not.  Should I open this issue on the repo for the code itself?

**Comment by rachaelshaw** [comment]
@songangel72 the reason why it's appearing as an object is because it's already been decoded by the time it reaches your client-side code; you don't need to use `JSON.parse()` on the client side

**Comment by songangel72** [comment]
@rachaelshaw I totally missed the fact that apparently my wrapper around the AJAX call was sending me parsed data.  Sorry to raise a non issue!
