### ISSUE TITLE
Docs External Linking Issue

### ISSUE THREAD

**Issue by knight-of-design** [balderdashy/sails-docs#323]
Not sure if this has been addressed, but since there isn't an open issue about this thought I'd mention it.

Whenever I try to visit links off of Google search, the link takes me to the concepts TOC and then I have to manually navigate (ie. figuring out which links to click) which gets annoying at times.  

It seems as though the documentation naming/structure has changed a little between versions and thusly fails to translate the old paths to the new ones.
 
It would be nice for us meek developers, if the links actually took you where they said they were going to go inside the docs instead of redirecting to the TOC.

An example case is below:
------Google Search: sails model -------
Models - Sails.js | Realtime MVC Framework for Node.js
sailsjs.org/#!documentation/models
Like most MVC frameworks, Sails provides an ORM (Object Relational Mapping) called Waterline for normalizing interactions with models, no matter what data ...
----Summary-----
Old URL:  http://sailsjs.org/#!documentation/models
New URL: http://sailsjs.org/#/documentation/concepts/ORM 

I know there are several strategies to handle this kind of issue. 

Thanks for your time.

**Comment by rachaelshaw** [comment]
#369, #372, #472 are all pretty much duplicates of this issue. Leaving this open, since it's the first chronologically, but I'm closing the rest so we can just track the Google indexing issue in one place.

**Comment by secrettriangle** [comment]
:+1:

**Comment by rachaelshaw** [comment]
Quick update on this: I've started working on [an update of sailsjs.org](https://github.com/balderdashy/www.sailsjs.org/tree/v1.0) that gets rid of all the angular client-side routing, so that The Google may smile upon us once more. Should be ready to go online fairly soon (hopefully).

**Comment by dbkaplun** [comment]
Just curious, why doesn't Angular suffice? Does no hash-dependent router suffice or is it just Angular?

**Comment by rachaelshaw** [comment]
No hash-dependent router will be crawlable without some extra help (there are some good tools out there  for this, such as [BromBone](http://www.brombone.com/), which we've used in the past). SEO isn't my area of expertise, but from what I understand Google considers anything after the # as part of the same page.

**Comment by rachaelshaw** [comment]
Going to go ahead and close this one now that the updated sailsjs.org is online. Looks like Google searches are starting to show the new links
![screen shot 2015-07-09 at 2 36 04 pm](https://cloud.githubusercontent.com/assets/3065949/8605046/0c974224-2648-11e5-8a33-102d3f323694.png)
