### ISSUE TITLE
Blueprint search by  date

### ISSUE THREAD

**Issue by oscarvegar** [balderdashy/sails-docs#324]
Hello, I want to achieve this using the BLUEPRINT API for a search by date...

http://localhost:1337/patient?where={"createdAt":{">":2014-10-30T22:09:59.364Z"}}

But it is impossible I tried to put ISODate or something, console throws this error...

Can't canonicalize query: BadValue Can't have RegEx as arg to predicate over field 'createdAt'.

Have a nice day!

**Comment by Dallas62** [comment]
`{"createdAt":{">":"2014-10-30T22:09:59.364Z"}}`

missing " ?

**Comment by jub3i** [comment]
Not related to sails-docs, Closing. Check out http://sailsjs.org/#!/support or migrate to https://github.com/balderdashy/waterline or an appropriate adapter repo.
