### ISSUE TITLE
Table of Contents should link to listed sections

### ISSUE THREAD

**Issue by ProLoser** [balderdashy/sails-docs#334]
Kind of annoying not being able to expand the nav or just click on items in the TOC. I tried editing it but realized that the TOC shows up in lieu of a 404 page everywhere, causing the links to be rather brittle, and you guys have this weird convention of using `0home/0home.md` when in all rationality it would make more sense to just treat a `README.md` or `index.md` as the default markdown file for every folder.

**Comment by rachaelshaw** [comment]
@ProLoser if you have time for a PR to update this, that'd be cool

**Comment by rachaelshaw** [comment]
TOC is clickable now. (Only on sailsjs.org; in this repo they're still just lists -- they aren't actually being used on the website anymore)
