### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by Industrial** [balderdashy/sails-docs#343]
Hi. I'm writing a small personal wiki and I want my Page model to have a title property that's a string that may contain slashes. I've adapted my frontend router (backbone) to do this but it seems (by the docs) that the sails router does not support splat routes e.g. `"get /page/*title"` that would match on `/page/Home` and `/page/Some/Levels/Down/In/The/Wiki`.

I've chosen to put the verb before the identifier in routes e.g. `/wiki/edit/Some/Levels`.

If there's a better way then I'd gladly accept suggestions :D

**Comment by jub3i** [comment]
Hi @Industrial issues logged here are for sails docs. In the docs under you will read you can use * in routes: http://sailsjs.org/#!/documentation/concepts/Routes/RouteTargetSyntax.html
