### ISSUE TITLE
Wrong path for http://sailsjs.org/#!documentation/guides/customBlueprints

### ISSUE THREAD

**Issue by Vadorequest** [balderdashy/sails-docs#345]
At http://sailsjs.org/#/documentation/reference/blueprint-api there is a link for http://sailsjs.org/#!documentation/guides/customBlueprints but it's broken.

> Alternatively, you can override the blueprint action everywhere in your app by creating your own custom blueprint action. (e.g. api/blueprints/create.js).

**Comment by rachaelshaw** [comment]
Looks like that page doesn't exist anymore. Updated that doc page.
