### ISSUE TITLE
Partials ejs

### ISSUE THREAD

**Issue by OSN64** [balderdashy/sails-docs#357]
It seems that in the documentation there may be a problem with how partials are explained cause 
``` ejs
<%- partial ('../../partials/widget.ejs') %>
```
should be 
``` ejs
<%- partial ('../partials/widget.ejs') %>
```
ive tested it .. mayby someone can try to replicate this

**Comment by rachaelshaw** [comment]
Looks like this was fixed in [this commit](https://github.com/balderdashy/sails-docs/commit/aed0b9c1c37f65fafee5adae498ed1b32b6b2330).
