### ISSUE TITLE
Documentation for Models in missing !!

### ISSUE THREAD

**Issue by nsisodiya** [balderdashy/sails-docs#373]
Here is the google cached version which is missing

http://webcache.googleusercontent.com/search?q=cache:vUquT5Su3VEJ:sailsjs.org/%23!documentation/models+&cd=1&hl=en&ct=clnk&gl=in&client=ubuntu

**Comment by jub3i** [comment]
Model docs are available at http://sailsjs.org/#!/documentation/concepts/ORM now.
