### ISSUE TITLE
Internal links in the documentation are broken

### ISSUE THREAD

**Issue by chr15m** [balderdashy/sails-docs#378]
For example, the link to 'Attributes' at the bottom of this page:

http://sailsjs.org/#/documentation/concepts/ORM/model-settings.html

The link to '.done() vs. .exec()' on this page:

http://sailsjs.org/#/documentation/concepts/Upgrading

**Comment by jwahdatehagh** [comment]
Seems like they introduced hashbangs for search engine crawlability. 
Maybe balderdashy could add something like this to the master template...

``` javascript
(function() {
  if(window.location.hash && window.location.hash[1] !== '!') {
    var path = window.location.pathname + window.location.hash.replace('#/', '#!/');
    window.location.replace(path);
  }
})();
```

**Comment by clay-to-n** [comment]
This was incredibly frustrating as someone trying to learn Sails.

The "Getting Started" guide on the website ends with a link to [this github page](https://github.com/balderdashy/sails-docs/blob/master/getting-started/getting-started.md), which doesn't direct you anywhere after you finish.  Is there no walkthrough?  Why has the documentation been broken for a month?  Does not inspire confidence in the framework.

**Comment by CWyrtzen** [comment]
tracking all of these down: https://github.com/balderdashy/sails/issues/2733

**Comment by rachaelshaw** [comment]
Closing this, because all of the links mentioned here are fixed at this point, and a lot of the formerly broken links now redirect to the right place.

There may still be a couple floating around that nobody's said anything about, so if anybody spots another broken link, PRs for that sort of thing are always appreciated.
