### ISSUE TITLE
[discussion] Lifting and lifecycle events

### ISSUE THREAD

**Issue by plato-cambrian** [balderdashy/sails-docs#386]
As a new Sails developer,  
I want to plug my own code into my Sails backend,  
so I can start a worker function when I run `sails lift`.

There are similar use cases for other lifecycle events like "sails is shutting down" or "grunt is about to begun" or "sails lift has completed".

I looked for the words "Lifting," "Lifecycle" and "Hooks" in Concepts but don't see anything.  
How can I run my code at appropriate times and where can I find the documentation?

**Comment by plato-cambrian** [comment]
I found it buried at http://sailsjs.org/#/documentation/reference/sails.config/sails.config.bootstrap.html , this was quite difficult to find without knowing what to look for

**Comment by loicsaintroch** [comment]
Does this file answers your question? Feel free to write a pull request on `sails-docs` if you think we can do better. We'll be glad to merge it.

**Comment by mikermcneil** [comment]
hi :)

simple answer: yup, bootstrap is the answer

for more control (custom hooks): https://github.com/balderdashy/sails-docs/tree/v0.11/concepts/extending-sails/Hooks

advanced/low-level (specific event names): https://github.com/balderdashy/sails/blob/master/lib/EVENTS.md

**Comment by mikermcneil** [comment]
thanks Loïc!

**Comment by plato-cambrian** [comment]
Thanks @loicsaintroch @mikermcneil
