### ISSUE TITLE
regarding req

### ISSUE THREAD

**Issue by kvbanantha** [balderdashy/sails-docs#389]
Everywhere in the document it is given that res.json but no information on what do we do with req object such as How do we extract req parameters etc. In realtime applications we extract some data from req and process the data. I am looking for some examples in this framework. Please provide me any examples how to get Values from req parameters and also how to set them in Views

**Comment by Dallas62** [comment]
http://sailsjs.org/#/documentation/reference/req/req.param.html ?

**Comment by jub3i** [comment]
missing bang in link: http://sailsjs.org/#!/documentation/reference/req/req.param.html
