### ISSUE TITLE
Url to 404 in docs

### ISSUE THREAD

**Issue by xeonarno** [balderdashy/sails-docs#404]
http://sailsjs.org/#/documentation/concepts/File-Uploads 

The link at the end of the page : Uploading to Amazon S3 push to a 404 page

**Comment by alexbaumgertner** [comment]
It must be this link https://github.com/balderdashy/skipper#uploading-files-to-s3, I guess.

**Comment by 6a68** [comment]
The problem seems to be that many of the links in the sails docs site insert `/#` instead of `/#!` at the base of the routes, like the one in the bug description.

**Comment by sgress454** [comment]
Thanks y'all, fixed here: https://github.com/balderdashy/sails-docs/commit/85777a94d5c4d7e54a06f2b84d090ed77bf56e22
