### ISSUE TITLE
Can someone please improve findOrCreate documentation?

### ISSUE THREAD

**Issue by megakoresh** [balderdashy/sails-docs#426]
Hey, sorry to bother ya'll, but I am really struggling to understand findOrCreate function and how it works when it actually DOES find the instance.

I posted a thread [here](https://groups.google.com/forum/#!topic/sailsjs/V85yHgkr-QM), but so far noone was able to answer that. I am just wondering what happens when the function finds a node. Will it pass the reference to found instance to the callback? The docs imply it won't, but it doesn't just return the instance either.

**Comment by sgress454** [comment]
Hi @megakoresh, I answered you on Google Groups.
