### ISSUE TITLE
No documentation of res.view( {layout: "layout-file.ejs"} );

### ISSUE THREAD

**Issue by abacaj** [balderdashy/sails-docs#430]
No where could I find that we can pass the layout to the view in the documentation.

```res.view( {layout: "path-to-layout-file.ejs"} );```

Took me a bit to figure this out.

**Comment by jub3i** [comment]
The information is buried away in a few places, see http://sailsjs.org/#!/documentation/anatomy/myApp/config/views.js.html and http://sailsjs.org/#!/documentation/concepts/Routes , I have additionally included it in the ./concepts/views/layouts section of the docs too - as that would be the logical place to go look if you wanted to specify a layout for a view.
