### ISSUE TITLE
Model Settings leads to 404

### ISSUE THREAD

**Issue by tjwebb** [balderdashy/sails-docs#443]
https://github.com/balderdashy/sails-docs/blob/master/reference/sails.config/sails.config.models.md

https://github.com/balderdashy/sails-docs/blob/master/#/documentation/concepts/ORM/model-settings.html

**Comment by jub3i** [comment]
Hi @tjwebb , the sails-docs repo is (at the moment) a supporting repo for balderdashy/www.sailsjs.org - if you goto http://sailsjs.org/#!/documentation/reference/sails.config/sails.config.models.html and click the same link it works as expected. There are plans to have sails-docs be an independent repo, you can read more at balderdashy/www.sailsjs.org#66
