### ISSUE TITLE
Core Concepts Doc missing '2. CORS' section.

### ISSUE THREAD

**Issue by sam-webdev** [balderdashy/sails-docs#446]
I noticed that http://sailsjs.org/#!/documentation/concepts is listed under the 'Table of Contents' but is completely missing '2. CORS' under https://github.com/balderdashy/sails-docs/tree/master/concepts.  Does this need to be removed from the 'Table of Content's of the site, or does this section need to be added to the github doc?

Thanks!

**Comment by rachaelshaw** [comment]
sailsjs.org is no longer using the table of contents in the sails-docs repo and instead is creating the table of contents dynamically, so it should be up to date now.

If you still feel like updating the TOC in the docs, I'll definitely merge a PR for that -- just know that it's only for the sake of the sails-docs repo and won't affect the website.
