### ISSUE TITLE
link works in md, but not on site

### ISSUE THREAD

**Issue by ezekeal** [balderdashy/sails-docs#457]
http://sailsjs.org/#!/documentation/anatomy/myApp/config/local.js.html

The link to the wiki article leaves off the parenthesis on your site. It works fine in the md file.

**Comment by rachaelshaw** [comment]
@mikermcneil @uncletammy I'm guessing this is something that need to be fixed in doc-templater, unless either of you have any ideas for working around it?

**Comment by rachaelshaw** [comment]
Changed that one to use an <a> tag instead of markdown. Its not live on the website yet, but I compiled the doc templates locally and tested it out, so should be fixed next time we deploy.
