### ISSUE TITLE
Is it possible to let user put example in the doc

### ISSUE THREAD

**Issue by northvik** [balderdashy/sails-docs#474]
I think it's really important to have a good doc. to have example and a search bar

**Comment by rachaelshaw** [comment]
@northvik if you'd like us to link to an example you made, we will gladly add it to the list of community tutorials [here](https://github.com/balderdashy/sails-docs/blob/master/FAQ.md#what-are-some-good-community-tutorials) if you submit a PR with the link. Thanks!
