### ISSUE TITLE
Links from Google search results are redirected to #/documentation/concepts

### ISSUE THREAD

**Issue by mikeyhew** [balderdashy/sails-docs#491]
When I search google for documentation on something in sails, something usually comes up from the sails documentation pages. But whenever I click on those links, it redirects to #/documentation/concepts page. It's really frustrating! Sometimes I have to resort to using Google's cached pages.

**Comment by rachaelshaw** [comment]
@mikeyhew this is fixed with the latest update of the sails website. Google may not have indexed all of the new documentation links yet, but a good number of them should work now at least.

**Comment by mikeyhew** [comment]
Awesome, it looks good! These new docs are way more informative. The links
in the source look like they're still old, but it seems they're redirecting
to the right place now.
