### ISSUE TITLE
Security dependencies

### ISSUE THREAD

**Issue by npoirier-palo** [balderdashy/sails-docs#492]
Hello

We noticed few problem with version 0.11 and  dependencies contains vulnerabilites detect by nsp (https://github.com/nodesecurity/nsp) details

Name          Installed       Patched         Vulnerable Dependency
qs                 0.5.6          >= 1.x             grunt-contrib-watch@0.5.3 > tiny-lr@0.0.4 > qs@0.5.6
serve-index     1.1.6       >=1.6.3           sails@0.11.1 > express@3.16.0 > connect@2.25.0 > serve-index@1.1.6
serve-static    1.5.4        >=1.7.2           sails@0.11.1 > express@3.16.0 > connect@2.25.0 > serve-static@1.5.4
send              0.8.1         >= 0.8.4          sails@0.11.1 > express@3.16.0 > send@0.8.1
semver          3.0.1         >=4.3.2           sails@0.11.1 > express-handlebars@1.0.3 > semver@3.0.1
semver          2.2.1         >=4.3.2           sails@0.11.1 > semver@2.2.1

For the next release is-it possible to fix the version ?

Thx and congratulations for the real good job with sailsjs !

Regards

**Comment by rachaelshaw** [comment]
@npoirier-palo closing this here, since it's not a documentation issue. I made an issue in the main sails repo for it.
