### ISSUE TITLE
Call multi layout on view.js in config forder

### ISSUE THREAD

**Issue by itplusvn** [balderdashy/sails-docs#498]
I have two forder in controller forder: admin and public.

I want to edit view.js file in config forder.

    if controllers file in admin forder, it call a layout: layout-admin

    if controllers file in public forder, it call a layout: layout-public

    but i don't know do it.

please support for me with this. thank a lot!

**Comment by duvillierA** [comment]
Try this :
```javascript
// AdminController.js
module.exports = {
  admin: function (req, res) {
    res.view({
      layout: 'layout-admin'
    });
  }
}
```

**Comment by rachaelshaw** [comment]
Thanks for helping out, @duvillierA. @itplusvn hope you were able to get it working alright.

(Closing this now since it's not a documentation issue.)
