### ISSUE TITLE
Links are broken because they route to beta.sailsjs.org

### ISSUE THREAD

**Issue by BastiPaeltz** [balderdashy/sails-docs#500]
Hey Sails-Team,

I am getting started with Sails.js (love it) and noticed that some links on the documentation are faulty and throw an 'The server can't be found' error because they are referenced to beta.sailsjs.org/rest_of_url. They work fine if one removes the 'beta.' from the URL.

**Comment by rachaelshaw** [comment]
@BastiPaeltz beta.sailsjs.org is now set up to redirect to sailsjs.org, so this should be fixed now. If you run into any more links in the docs that start with 'beta', a PR fixing it would be very much appreciated. :)
(If you're on the website, there should be a link at the bottom of each doc page that takes you to the right file to edit.)
