### ISSUE TITLE
Broken link for hook specification

### ISSUE THREAD

**Issue by IanVS** [balderdashy/sails-docs#507]
The [hooks page](http://www.sailsjs.org/documentation/concepts/extending-sails/hooks) has broken links in various locations for the hook specification:

http://www.sailsjs.org/documentation/concepts/extending-sails/Hooks/hookspec

I believe the link should be changed to:

http://www.sailsjs.org/documentation/concepts/extending-sails/hooks/hook-specification

**Comment by rachaelshaw** [comment]
@IanVS thanks for pointing this out. If you have a second to submit a PR fixing it, would be much appreciated. :)
(If you follow the link under the "Is something missing?" header at the bottom of the page with the broken links, it should bring you to the file in this repo to edit.)

**Comment by IanVS** [comment]
Sure, and I found a few others as well. Do you require an issue for each PR?

Also, what is the story with hashbangs in urls? Should they be used in links, or no?

**Comment by rachaelshaw** [comment]
@IanVS don't need issues for each PR if it's just little changes like fixing links.

re: hashbangs, when updating old/broken links we shouldn't use them anymore, but we're redirecting the old hashbang urls to the right pages for the most part, so there isn't a huge hurry to switch them over to the newer way.
