### ISSUE TITLE
One-to-many associations doc link broken

### ISSUE THREAD

**Issue by migue1s** [balderdashy/sails-docs#519]
On http://sailsjs.org/documentation/concepts/models-and-orm/associations/one-to-many clicking the 
`For a more detailed description of this type of association, see the Waterline Docs` is broken.

It redirects to: 
* https://github.com/balderdashy/waterline-docs/blob/master/associations.md

It should redirect to:
* https://github.com/balderdashy/waterline-docs/blob/master/models/associations/associations.md

**Comment by irlnathan** [comment]
Thank you for this...it's been updated.
