### ISSUE TITLE
Who is Timothy the Monkey?

### ISSUE THREAD

**Issue by brettimus** [balderdashy/sails-docs#524]
[The concept page on models](http://sailsjs.org/documentation/concepts/models-and-orm/models) has a link to a story about "Timothy the Monkey." 

Unfortunately, this link does not go anywhere! I want to know about Tim!! My google search was fruitless.

:monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:

**Comment by rachaelshaw** [comment]
Duplicate of #400 -- closing this so we can move all discussion to that issue.
Timothy would have wanted it that way.

**Comment by brettimus** [comment]
Should have done a search- my b. :see_no_evil: 

Send Tim my regards
