### ISSUE TITLE
`skipRegex` takes a `RegExp`, not `Boolean`

### ISSUE THREAD

**Issue by brettimus** [balderdashy/sails-docs#525]
[The custom routes documentation](http://sailsjs.org/documentation/concepts/routes/custom-routes) lists the type of `skipRegex` as `bool`.

I looked at the markdown, and I'm unfamiliar with the syntax that's being used to specify types `((bool))`. Down to fix this once I find out which markdown parser the site uses :grin:

**Comment by rachaelshaw** [comment]
We're using [uncletammy/doc-templater](https://github.com/uncletammy/doc-templater), but `((someType))` is being converted into those type bubbles in the [sails website project](https://github.com/balderdashy/www.sailsjs.org). If you change the type in that file, I'll just go in and add some kind of icon for it in the styles.

**Comment by brettimus** [comment]
alrighty! i still had trouble building. opened an issue on `doc-templater`, but i know you all are busy with, ya know, not the docs.

once i get a local build i can close #523 

but. well... [i need help](http://media3.giphy.com/media/Id6RRFgZ3HGaQ/giphy.gif)
