### ISSUE TITLE
"Models and ORM" mentions connections.js, which doesn't exist

### ISSUE THREAD

**Issue by fzero** [balderdashy/sails-docs#539]
Whenever a new 0.11.x app is created, there's no connections.js. The config seems to be in adapters.js now, but the way the object is formatted is slightly different.

Speaking of which, it would be beneficial to have an example on how to setup a database connection that doesn't need username/password - such as local Postgres installations. Should the parameters be blank? Set to empty strings? `null`s?

**Comment by irlnathan** [comment]
Hi Fabio,

I'm running the latest published Sails 0.11.0.  New apps (for me) have a project/config/connections.js file.  Are you seeing no connections.js file in one of the later repo builds?

I'll add some verbiage on how to set-up postgresql without a password.  To answer your question though, you can just remove the property (e.g. password) and it will work without it so long as the user doesn't have a password.

**Comment by fzero** [comment]
It looks like it was my fault. I had a weird npm version conflict going on and the `sails` command was running version 0.9.7, which explains everything. Sorry about the hassle!

**Comment by irlnathan** [comment]
Not at all.  I'm really interested if you find an issue with the docs, please keep posting.
