### ISSUE TITLE
no listing for model types OR the documentation site needs a search facility

### ISSUE THREAD

**Issue by ogrotten** [balderdashy/sails-docs#581]
```
module.exports = {
  attributes: {
    filename : { type: 'string' },
  }
};
```
For the `type` entry in this snippet, there's no entry in the docs for a list of types available. 

If there is, it's not under Waterline or either of the models entries in the docs.

**Comment by jub3i** [comment]
http://sailsjs.org/documentation/concepts/models-and-orm/attributes - maybe you missed it when you checked the docs :)

**Comment by ogrotten** [comment]
Came back to say thank you. . .

. . .and to leave the 2ndary request for a search box on the docs (=

**Comment by jub3i** [comment]
@ogrotten Pull requests for that search box are welcome :D
