### ISSUE TITLE
Does model.query() method return a promise?

### ISSUE THREAD

**Issue by yunjiali** [balderdashy/sails-docs#619]
It seems to me that model.query() method doesn't return a promise at the moment, unlike find(), findOne(), etc.

http://sailsjs.org/documentation/reference/waterline-orm/models/query
http://stackoverflow.com/questions/21886630/how-to-use-model-query-with-promises-in-sailsjs-waterline

I am using sails v0.11.2. Should this be added this into the doc?

**Comment by brettimus** [comment]
About to hop on a :airplane:, but a quick glance at waterline + the current postgres adapter seems to confirm your intuition. 

Not sure about other folks, but I do think that'd be a useful addition to the docs! Wanna submit a PR?

_References_

[Here](https://github.com/balderdashy/sails-postgresql/blob/master/lib/adapter.js#L137) is where `#query` is defined in one of the SQL adapters (for postgres). Clearly, does not return a promise. However, if you look at the other parts of the interface that we'd expect to return a promise, they don't either. That leads us to waterline itself... 

[This](https://github.com/balderdashy/waterline/blob/master/lib/waterline/adapter/dql.js) is what seems to promisify a given adapter's interface. From what I can tell, it doesn't promisify the `native` or `query` methods, which are specific to nosql / sql. 

My **disclaimer** here is this is the product of < 15 mins of research. So I might be totally and completely wrong about everything every :dizzy: :grin:

**Comment by mikermcneil** [comment]
@brettimus :+1: You are totally right.

@yunjiali this would be an excellent correction, thanks for bringing it up!  Echoing @brettimus in that we would greatly appreciate PR if you wouldn't mind adding a note to the reference page you linked to.

**Comment by yunjiali** [comment]
@brettimus @mikermcneil Thank you for your quick responses. I will add the following sentence in the Notes section:

At the moment, you have to provide the callback function as the second parameter in order to access the query error and results. Please refer to [this link](http://stackoverflow.com/questions/21886630/how-to-use-model-query-with-promises-in-sailsjs-waterline), if you want this method to return a promise.  

Please feel free to correct me if there is anything wrong. If this sounds good for you, I will generate a pull request soon. Many thanks.

**Comment by brettimus** [comment]
Nice touch with the SO link! 

My only tweak would be to the lead with the meat of the sentence. So, under the *Notes* section, add:

* This method does not return a promise. [Refer here](http://stackoverflow.com/questions/21886630/how-to-use-model-query-with-promises-in-sailsjs-waterline) to promisify `.query()`.

Can't wait to merge your PR :smile_cat:

**Comment by brettimus** [comment]
`promisify` is a silly phrase

:mega: shout out to whoever invented that phrase

**Comment by mikermcneil** [comment]
@yunjiali @brettimus :+1: :loudspeaker: :notes: :camel:

**Comment by yunjiali** [comment]
@brettimus your version is much better than mine :+1: The pull request has been created. Many thanks for all your help.

**Comment by brettimus** [comment]
Woohoo! Thanks for the catch @yunjiali and double thanks for the contribution

**Comment by yunjiali** [comment]
@brettimus My pleasure :=)
