### ISSUE TITLE
Load order and .sailsrc options

### ISSUE THREAD

**Issue by Boycce** [balderdashy/sails-docs#625]
Hey there,
Would be great to have some sort of documentation on the *load order* of sails. For example I was trying to console out some information in `config/bootstrap.js` but couldn't see the log due to an error further up the chain in `services/passport.js`. I just presumed config files were loaded first.

Also I never knew you could define custom paths for most of sails in `.sailsrc` until i read this [issue](https://github.com/balderdashy/sails/issues/3325#issuecomment-151069080). Maybe, if more configurations exist, having them documented [here] (http://sailsjs.org/documentation/reference/configuration/sails-config) e.g sails.config.paths

**Comment by mikermcneil** [comment]
Hey @Boycce!

re: `sails.config.paths` -- definitely could use a page there (I was _positive_ we had one, but apparently I've completely lost my mind).  I'll add a page asap and clarify that paths can only be configured before the `userconfig` hook is loaded-- i.e. sailsrc file, programmatically, or env vars.


re: .sailsrc and load order:
We may actually already have that covered as far as configuration load order goes ( http://preview.sailsjs.org/documentation/reference/configuration and http://preview.sailsjs.org/documentation/concepts/configuration ) -- let me know what you think.


But we could certainly use more info on the way the moduleloader works in general.  I would say we're not screaming from the rooftops about "don't put code other than require()s in your Sails modules outside of functions!" as much as we ought.  Where would you say that sort of info should go-- maybe `sailsjs.org/documentation/concepts/modules`?

Thanks!

**Comment by mikermcneil** [comment]
@Boycce just had an epiphany about where there are some more detailed docs on internal load order within Sails core: https://github.com/balderdashy/sails/tree/master/lib/app

There are also a few other README files throughout Sails core that might be helpful.  I tried to add them wherever I could (they should be mostly up to date)

**Comment by mikermcneil** [comment]
@Boycce Ok, we added a new section about this to the docs for 0.12 (https://github.com/balderdashy/sails-docs/blob/64e1eeb4817927db70b2f1afc4e1ae547923dcf8/reference/application/lifecycle.md). It's based on what you probably already read in the README within Sails core, but wanted to link it for you asap in case it provides additional insight.

Also, @luislobo set up a first pass at a [sequence diagram](https://www.websequencediagrams.com/?lz=dGl0bGUgU2FpbHMuanMgTGlmdCBsb2FkIG9yZGVyCgpzYWlscy1saWZ0LT4rcmNvbmY6PDxjb25zdHJ1Y3Rvcj4-Cm5vdGUgcmlnaHQgb2YgAB4GAD4FLgA4BXJjLCBlbnYsIGV0YwoAPQUtPi0ATQo6AFAFAFoPY2FwdGFpbi1sb2c6cmVxdWlyZSgnAAoLJykoAIEHBS5sb2cpCgAjCwBNDmxvZwoAgRAPAG4LTG9hZCBsb2NhbCBub2RlX21vZHVsZXNcbgCCCQUgb3IgZ2xvYmFsAIIYBgCBfA8Agi0FAIF6EQoAgkQFAIEcJQCBJw8ASgYAgmkFLgCBMgUAQghSb3V0ZXI6AAEGKHRoaXMpAIJjDwAbB3NldHMgZGVmYXVsdCA0MDQsIDUwMAAVFmluc3RhbnRpYXRlcyBFeHByZXNzKCkKAGUGAH4PcgB7BQCDVg8AgScHZXRzIHVwIG1ldGhvZHMAgXYIAINRDgCEPAUAgigVbGlmdChzY29wZSkAgi8JABMHb2FkKGNvbmZpZwCBXRAAgnIGTG9hZHMgABwGdXJhdGlvbgCBDRVJbml0aWFsaXplIGhvb2tzAIMYCACCaAcAgyYKAINJBmkAJgkoKQCEKRAAgWoJIHVwIFNpZ25hbHNcblNJR1VTUjIABAVJTlQADAVURVJNAIQBCACEIQZib290c3RyYXAoAIE5FgCDcQZlbWl0KCdyZWFkeScpAIRCCQCBIgkAGSBsaWZ0ZWQnKQo&s=qsd).  It needs to be abstracted a bit further to be generally useful imo, but I thought it was a pretty cool way to visualize thigns.

**Comment by mikermcneil** [comment]
@Boycce alrighty, this is live on the website: http://sailsjs.org/documentation/reference/application/lifecycle

**Comment by Boycce** [comment]
Perfect, the lifecycle page brings a great overview! Maybe also mention that the user configurations load in chronological order, minus `sails.config.bootstrap`. The latter isn't a necessity as you state its entry on the last step.
