### ISSUE TITLE
upload file

### ISSUE THREAD

**Issue by quannhan1226** [balderdashy/sails-docs#636]
Field one input type="field" name="avatar1"
Field two input type="field" name="avatar2"
Field submit   type="submit" name="upload"
I can use req.file('avatar1').upload and I use req.file('avatar2').upload.
Error 
Please help me propblem above

**Comment by mikermcneil** [comment]
Hi @quannhan1226 -- answered you in Gitter:
https://gitter.im/balderdashy/sails?at=56b48ac0073653e7151bdf9e

**Comment by quannhan1226** [comment]
thanks but myproblem cannot resolve
