### ISSUE TITLE
Sessions documentation asks to install non-existent version of connect mongo

### ISSUE THREAD

**Issue by elssar** [balderdashy/sails-docs#641]
In the [sessions documentation](http://sailsjs.org/documentation/reference/configuration/sails-config-session#?using-other-connectcompatible-session-stores), it is recommended that users install version version 0.8.4 of connect-mongo to use mongo as the session store. But there is no version 0.8.4 for connect-mongo

**Comment by brettimus** [comment]
Looks like the closest version is `0.8.2` (see: [here](https://github.com/kcbanner/connect-mongo/releases)).

I'll change the docs to reflect this, but it'd probably be best to also confirm this example still works.

**Comment by brettimus** [comment]
@elssar Thanks for pointing this out! Were you able to set up a mongo session store?

**Comment by brettimus** [comment]
Hmmm looks like the docs might be out of sync. Waiting to see how [this issue](https://github.com/balderdashy/sails/issues/3574) on the sails repo gets resolved.

**Comment by elssar** [comment]
@brettimus I was answering a question on stackoverflow and the guy who asked the question noticed the error. I don't think he was able to get the mongo session store to work

**Comment by brettimus** [comment]
Looks like d16dcb7 fixed this. Closing!
