### ISSUE TITLE
Installable hooks documentation does not mention how to include scoped hooks

### ISSUE THREAD

**Issue by elssar** [balderdashy/sails-docs#644]
By default, the `loadUserHooks` method in the `moduleloader` hook checks checks only the sub directories of `node_modules` for installed hooks. But scoped packages (`@scope/sails-hook-something`) are a level deeper, and aren't loaded.

The documentation mentions that we can use the `sails.hookName` key in `package.json` to  override the name of the hook, which can be useful while using scoped packages, but nowhere does it mention how to load scoped hooks.

**Comment by sgress454** [comment]
Hm, scoped packages definitely should be loaded as of Sails 0.11.5.  There's a number of tests for it.  And you shouldn't have to override the name unless you don't want to override the core hook; for example `@myawesomeorg/sails-hook-csrf` should automatically override the core `csrf` hook.  If you're having issues loading scoped modules and you're using Sails >= 0.11.5, please post an issue in the Sails repo with more details!
