### ISSUE TITLE
Unclear how Policies are mapped to generated API

### ISSUE THREAD

**Issue by AskYous** [balderdashy/sails-docs#758]
http://sailsjs.org/documentation/concepts/policies 

For the policies page, it should mention how to map policies to API requests that were generated using `sails generate api <model>`. If it's not supported, it should say that too.

**Comment by mikermcneil** [comment]
Hey @AskYous, thanks for the feedback!  To answer your question directly, the built-in blueprint API is implemented using regular Sails controller actions.  So your policy mappings should work exactly the same, but pointing to the relevant blueprint actions (e.g. `UserController.findOne`).

Sounds like maybe what we need to do is:

1. Add a section (e.g. "Using policies with the blueprint API") fleshing out what I mentioned above, and walking through a quick example for clarity.
2. On [**Reference > Configuration > sails.config.policies**](http://sailsjs.org/documentation/reference/configuration/sails-config-policies), add a short 1-2 sentence blurb and link to the relevant permalink for the new section in [**Concepts > Policies**](http://sailsjs.org/documentation/concepts/policies)

Does that sound right?

**Comment by AskYous** [comment]
Yes, that sounds right!
![image](https://cloud.githubusercontent.com/assets/791996/19336498/c7265b6e-90c0-11e6-976e-a78f126ed620.png)

**Comment by rachaelshaw** [comment]
Fixed by https://github.com/balderdashy/sails-docs/commit/cd0754811e6958a13165fdf2e3bc4de9377c7608

**Comment by mikermcneil** [comment]
@rachaelshaw @AskYous thanks!
