### ISSUE TITLE
Adding middleware to private routes

### ISSUE THREAD

**Issue by jpravetz** [balderdashy/sails-docs#770]
Is there a way to add middleware to socket routes?
There appears to be a private router used for routes over socket.io, but I am not seeing how to add custom middleware to these routes?
Background: I have a logger that I attach to express req objects. I want to use this to log routing information for all non-asset requests. This requires attaching it to socket req objects, and being able to say which http routes to apply the middleware to.

**Comment by mikermcneil** [comment]
@jpravetz In the past, I used to recommend policies for this, but I was wrong.  Nowadays, I always recommend using a hook.  

This is just a quick scribble, but I think it'll do what you need if you create it at `api/hooks/request-logger/index.js`:

```js
/**
 * request-logger hook
 *
 * @description :: A hook definition.  Extends Sails by adding shadow routes, implicit actions, and/or initialization logic.
 * @docs        :: http://sailsjs.com/docs/concepts/extending-sails/hooks
 */

module.exports = function defineRequestLoggerHook(sails) {

  return {

    /**
     * Runs when a Sails app loads/lifts.
     *
     * @param {Function} done
     */
    initialize: function (done) {

      sails.log.debug('Initializing custom hook (`request-logger`)');

      // any stuff you want to happen as soon as sails loads

      // Be sure and call `done()` when finished!
      // (Pass in Error as the first argument if something goes wrong to cause Sails
      //  to stop loading other hooks and give up.)
      return done();

    },

    routes:{
      before: {

        'all /*': {
          skipAssets: true,
          fn: function (req, res, next){
            
            //  >> Log your stuff right here <<

            if (req.isSocket){
              // >> do any extra socket-only stuff here <<
            }
            else {
               // >> log any extra non-socket-only (e.g. HTTP-only) stuff here
             }

            return next();
          }
        }//</shadow route: all /* >

      }//</.routes.before>
    }//</.routes>

  };

};
```

**Comment by mikermcneil** [comment]
@jpravetz btw I just remembered:  whenever I've done what you're doing in the past, I always find myself wanting to log response metadata as well (e.g. status code that was returned and so forth).  If you find yourself needing that, check out https://github.com/balderdashy/sails-hook-dev/blob/7edd086e66e8a428f27859cda02a5b988cc14ad9/index.js#L109-L140

**Comment by mikermcneil** [comment]
@jpravetz AHA vaguely remembered actually putting this somewhere, and sure enough

See also https://github.com/balderdashy/sails-hook-dev/issues/2

**Comment by mikermcneil** [comment]
@jpravetz I just published a new version of sails-hook-apianalytics: https://github.com/mikermcneil/sails-hook-apianalytics


If you'll give that a go, I think it overlaps enough with what you're after that you'll be good to go.  Let me know how it goes!

**Comment by jpravetz** [comment]
I will do and report back here. Thanks.

**Comment by jpravetz** [comment]
@mikermcneil your request-logger example is exactly what I needed for sockets. For regular routes I am adding a customMiddleware method to sails.config.http. 

I'm using the [epdoc-logger](https://www.npmjs.com/package/epdoc-logger) for all of our logging. It has some very cool properties for adding logging on a per-request basis (eg. reqId and sessionId) and adding logging methods to the request object and logging metadata.

I've added sailsjs integration information to the epdoc-logger README and added your request-logger (with modifications) to the examples folder. 

Thanks for your help!
