### ISSUE TITLE
Inconsistent documentation about referencing models in attribute tags

### ISSUE THREAD

**Issue by grantrobertsmith** [balderdashy/sails-docs#831]
In many places, examples of collections use uppercase names.

e.g. 
```
enrolledIn: {
  collection: 'Course', via: 'students'
}
```

However, concepts/ORM/Associations/Associations.md says that it's important to reference them by lowercase name. It should be clarified why this is important or removed from the documentation.

**Comment by rachaelshaw** [comment]
@grantrobertsmith it looks like that note was updated [on the 1.0 branch](https://github.com/balderdashy/sails-docs/blob/1.0/concepts/ORM/Associations/Associations.md) -- is that the sort of clarification you had in mind? (These updates will make it into the main docs eventually)

**Comment by grantrobertsmith** [comment]
Yeah, that's perfect. Can you provide any further specification on 'eventually'? Would you recommend referencing both versions of the docs when I'm trying to learn/understand things in the future? Are there other branches I should heed?

**Comment by grantrobertsmith** [comment]
A reply to the previous comment would be great, but I'll go ahead and close this since the issue has indeed been addressed 'eventually'.
