### ISSUE TITLE
options.where doesn't work on update blueprint

### ISSUE THREAD

**Issue by PookMook** [balderdashy/sails-docs#866]
There is a problem on sails-docs/reference/req/req.options/req.options.where.md : 

This doesn't work on update as of mai 25th 2017,

We need to change the doc or make the feature work in sails

to make this work on update, we need to change :

```
    // Use existing req.options.where, or initialize it to an empty object
    req.query.where = req.query.where || {};
    // Set the default `userId` for "find" and "update" blueprints
    req.query.where.id_user = req.session.user.id_user;
```
or

blueprints/actionUtil.js (line 224):
```
    // Look for explicitly specified `where` parameter.
    var where = req.params.all().where;
```
to

```
    // Look for explicitly specified `where` parameter.
    var where = req.options.where;
```
as well as blueprint/actions/update.js (line 51)
`var query = Model.findOne(pk);`
to
`var query = Model.findOne(pk).where( actionUtil.parseCriteria(req) );`

Edit :
Managed to get a policy to work on find/update (but is no more tied to a where clause, so not good for the doc)
 
    //find model requested
    var Model = req._sails.models[req.options.model];
    //find the instance of the model requested
    Model.findOne(req.params.id).exec(function(err,record){
      if(err){return res.forbidden({message:'Error.'})}
      else if(!record){return res.forbidden({message:'no record found.'})}
      else{
        if(req.session.user && record.id_user === req.session.user.id_user){
          //owns this, pass to the next policy
          next();
        }
        else{return res.forbidden({message:'you do not own this record.'})}
      }
    });

**Comment by rachaelshaw** [comment]
@PookMook thanks for finding this -- you're right, this isn't supported. I'd accept a pull request updating this comment in sails core. (Closing this issue here because I don't believe it's documented anywhere in the actual documentation files, only in the comments -- let me know if I'm mistaken and you've seen it in the docs somewhere though.)
