### ISSUE TITLE
No link to documentation of default methods on Waterline Models on Models Concepts page

### ISSUE THREAD

**Issue by wyqydsyq** [balderdashy/sails-docs#868]
The default model class methods aren't mentioned on the Concepts page aside from this brief mention:

> Model class methods are functions built into the model itself that perform a particular task on its instances (records). This is where you will find the familiar CRUD methods for performing database operations like .create(), .update(), .destroy(), .find(), etc.

In http://sailsjs.com/documentation/concepts/models-and-orm/models#?model-methods-aka-static-or-class-methods

There should really be a link to the [relevant reference page](http://sailsjs.com/documentation/reference/waterline-orm/models) in that same section so users can naturally delve deeper into the API reference from that related Concepts page.

**Comment by rachaelshaw** [comment]
@wyqydsyq thanks for the feedback -- I just had a look at the 1.0 branch of the docs, and that page has changed quite a bit and now links to the reference section, so I'm going to consider this fixed. (The 1.0 docs will be moved onto master and be on the main website once 1.0 is officially released)
