### ISSUE TITLE
.create doesn't return the object just created

### ISSUE THREAD

**Issue by nghiadoan91** [balderdashy/sails-docs#870]
Hi, I tried to do 
Employee.create(model).exec(function(err,result){
if (err) {
                console.error(err)
                return res.serverError(err);
            }
            console.log(result);
            return res.json(result);
});
 and its giving me back undefined

**Comment by rachaelshaw** [comment]
@nghiadoan91 are you using the1.0 beta? If so, you'll need to include the `fetch` meta key to get the created record back:
```js
Employee.create(values)
.meta({fetch: true})
.exec(function(err,result){
  if (err) {
    console.error(err)
    return res.serverError(err);
  }
  console.log(result);
  return res.json(result);
});
```
Sails 1.0 docs for .create() are [here](http://next.sailsjs.com/documentation/reference/waterline-orm/models/create).
