### ISSUE TITLE
Socket documentation is not clear

### ISSUE THREAD

**Issue by praveen4554** [balderdashy/sails-docs#923]
I would like to integrate sails with web sockets i didn't find any github repo which is working and there is no clear documentation for adding configurations in server side . uploaded my project in the the github can you please update the settings for webscokets that will help us https://github.com/praveen4554/sails-swagger or 
Can you provide me clear documentation for the sockets in the server

**Comment by sgress454** [comment]
Hi @praveen4554, sorry you're not finding the Websockets docs clear enough.  If you have more specific suggestions about what's missing, please open a new ticket with those suggestions so we can act on them.  In the meantime, you can check out the [sailsChat](https://github.com/sgress454/sailsChat) (for Sails v0.12.x) or [sailsChat-1.0](https://github.com/sgress454/sailsChat-1.0) repos for examples of using sockets with Sails.  For a more full-featured 1.0 example app using sockets, check out [Chatkin](https://github.com/mikermcneil/chatkin).

**Comment by praveen4554** [comment]
Can you provide any git hub link for all the options using socket and also I am trying to use angular sockets for UI, I am unable to find a way to figured out. Right now I am using sails socket with sails client and I am exploring for publish create, update,delete I am exploring there is no easy way to find git hub link to use those options
