### ISSUE TITLE
Remove sails-hook-validation section information from docs

### ISSUE THREAD

**Issue by GoldenRust** [balderdashy/sails-docs#926]
In sails 1.0.0-37 custom validation messages with the ` sails-hook-validation` package doesn't work.

Can be misleading until it's fixed.

**Comment by Bot052179** [comment]
![2e40180a-3deb-4fa2-abf2-10e0700262b8](https://user-images.githubusercontent.com/8918699/32204555-51949036-bdc0-11e7-9132-def4757681be.jpg)

**Comment by rachaelshaw** [comment]
thanks @GoldenRust. Do you remember where this was mentioned?

**Comment by GoldenRust** [comment]
@rachaelshaw It's at the bottom under concepts > models and orm > validations
[Link here](https://next.sailsjs.com/documentation/concepts/models-and-orm/validations)

Will custom validations be part of sails v1, or will it still be an external package?

**Comment by rachaelshaw** [comment]
Fixed in https://github.com/balderdashy/sails-docs/commit/cb1220e9d5007597e255e58daa46d3e1a643b141

And v1 won't have custom error messages: check out @mikermcneil's comment [here](https://github.com/balderdashy/sails/issues/3459#issuecomment-344640065) for the reasoning behind this
