### ISSUE TITLE
Condtions for fieldA=fieldB

### ISSUE THREAD

**Issue by javahook** [balderdashy/sails-docs#956]
Asume....
table : student
fields:  fieldA; fieldB

where = ' fieldA=fieldB'

**Comment by rachaelshaw** [comment]
@javahook what page of the docs did you find an issue?

**Comment by javahook** [comment]
Sorry! Not an issue. just a question when I use the waterline query.

**Comment by rachaelshaw** [comment]
@javahook in the future I'd recommend the [Gitter channel](https://gitter.im/balderdashy/sails) to get help quicker -- we're not usually able to answer questions in GitHub issues.

Currently, Waterline doesn't support that type of query. We'd recommend trying to tweak your query to work around it if at all possible, but if you absolutely need it to be that way you can use a native query instead.

(Also, if you want more info about what's on the horizon in terms of Waterline, you can check out the [Sails roadmap](https://trello.com/b/s9zEnyG7))
