### ISSUE TITLE
Errors for Action exits are they needed?

### ISSUE THREAD

**Issue by elipeters** [balderdashy/sails-docs#993]
The docs are a bit vague but I assume you are handling errors internally or do we have to declare them as an exit?

Loving v1.0 btw!

**Comment by rachaelshaw** [comment]
@elipeters glad you're happy with 1.0!

Errors that aren't explicitly handled will exit through the default "error" exit (more info [here](https://sailsjs.com/documentation/concepts/actions-and-controllers#?exit-signals)), but it's always good to define exits for errors you want to handle in a specific way.
