### ISSUE TITLE
Error In add/remove Blueprint Routes?

### ISSUE THREAD

**Issue by rajaie** [balderdashy/sails-docs#995]
On this page (https://github.com/balderdashy/sails-docs/blob/master/reference/blueprint-api/Add.md), the route for adding a record to a collection looks like:

`PUT /:model/:id/:association/:fk`

But here (https://github.com/balderdashy/sails-docs/blob/master/concepts/Blueprints/Blueprint%20Routes.md), the route is:

`PUT /boat/:id/drivers/add/:fk`

Notice the extra /add/ in the path.

The `remove` action has the same discrepancy (and also shows `add` instead of `remove`). Is this an error, or does this work both ways?

**Comment by rachaelshaw** [comment]
@rajaie thanks for pointing out the inconsistency -- the reference docs are correct.  I fixed those routes in the concepts docs: https://github.com/balderdashy/sails-docs/commit/c1c8d53a77c5c9b03689fdd7f3a65a2d87d2e9ba
